// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiMybr1zGLyi_oZ_9zBN4A7DjyLaYMybo',
    appId: '1:522343552464:web:92cffade3d8feb695e55d5',
    messagingSenderId: '522343552464',
    projectId: 'calendar-scheduler-a58e9',
    authDomain: 'calendar-scheduler-a58e9.firebaseapp.com',
    storageBucket: 'calendar-scheduler-a58e9.appspot.com',
    measurementId: 'G-4MZ4Y0HXLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqTxHCr2stcrQF8QI7oNPOSy7LBzXQ1mY',
    appId: '1:522343552464:android:14b1ee4fb94756a55e55d5',
    messagingSenderId: '522343552464',
    projectId: 'calendar-scheduler-a58e9',
    storageBucket: 'calendar-scheduler-a58e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsEtcyX2DHyaZCxNHaHZH7hJPs2t70I3M',
    appId: '1:522343552464:ios:e1f673c61c374eb65e55d5',
    messagingSenderId: '522343552464',
    projectId: 'calendar-scheduler-a58e9',
    storageBucket: 'calendar-scheduler-a58e9.appspot.com',
    iosClientId: '522343552464-5slg66t0bd9a13r5i5ev83pib2rin9t9.apps.googleusercontent.com',
    iosBundleId: 'com.deutschkihun.scheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsEtcyX2DHyaZCxNHaHZH7hJPs2t70I3M',
    appId: '1:522343552464:ios:d901c6c1828b4afd5e55d5',
    messagingSenderId: '522343552464',
    projectId: 'calendar-scheduler-a58e9',
    storageBucket: 'calendar-scheduler-a58e9.appspot.com',
    iosClientId: '522343552464-61fv12pn1ktecnus074qq2i8ceffsqbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.scheduler.RunnerTests',
  );
}
